apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    build.appstudio.openshift.io/application: my-application
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: my-component
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: appstudio
  namespace: hacbs-748
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
status: {}
