apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: my-component
  namespace: hacbs-748
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: my-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: my-component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: my-component-
      labels:
        build.appstudio.openshift.io/application: my-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: my-component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: hacbs-748
    spec:
      params:
      - name: git-url
        value: https://github.com/lcarva/minimal-container.git
      - name: output-image
        value: quay.io/lucarval/minimal-container-hacbs:latest-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:ad4c34b71d468a991450b0091cd96765471ed82d
        name: noop
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: my-component/$(tt.params.git-revision)
    status: {}
status: {}
