apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: my-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: my-component
    app.kubernetes.io/part-of: my-application
  name: my-component
  namespace: hacbs-748
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: my-component
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-component
    spec:
      containers:
      - image: quay.io/lucarval/minimal-container-hacbs
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
